version: '3'

services:
#  db:
#    image: mysql
  web:
    build: .
#    command: python3 mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    stdin_open: true
#    depends_on:
#      - db
