version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Saphira10
      - MYSQL_DATABASE=django-tutorial
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
    command: mysqld --default-authentication-plugin=mysql_native_password
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: tail -F anything
